In [1]:
#using numpy for matrices in python

import numpy as np

In [7]:
#creating matrices using numpy

revenue = np.array([[80,150,200],[70,140,190],[90,160,210]])
expense = np.array([[40,75,100],[30,65,90],[50,85,110]])

print(revenue)

[[ 80 150 200]
 [ 70 140 190]
 [ 90 160 210]]


In [10]:
#simple matrix subraction 
# matrix multiplication and addition are similar

profit=revenue-expense
print(profit)

[[ 40  75 100]
 [ 40  75 100]
 [ 40  75 100]]


In [11]:
#Dot product in numpy 

price = np.array([[80,150,200]])
units = np.array([[40,75,100],[30,65,90],[50,85,110]])

np.dot(price,units)


array([[17700, 32750, 43500]])

In [14]:
#excersise -> converting indian rupees into us Dollar

inr = np.array([[40,75,100],[30,65,90],[50,85,110]])

# 1 usd = 75 inr

print(inr*75)

[[3000 5625 7500]
 [2250 4875 6750]
 [3750 6375 8250]]
